name: build
# From now in android
# https://github.com/android/nowinandroid

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'app-ios/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - uses: ./.github/actions/setup-java

      - run: ./gradlew :app-android:assembleDevDebug --stacktrace

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs
          path: app-android/build/outputs
          retention-days: 14
