name: iOS Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java
      - run: make build-app-debug
        working-directory: app-ios
      - run: make test-app-debug
        working-directory: app-ios
      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: app-ios-shared-xcframework
          path: app-ios-shared/build/XCFrameworks
