name: save-pr-number-for-removing-waiting-label

on:
  pull_request:
    types: [synchronize]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [ created ]

jobs:
  save_pr_number:
    runs-on: ubuntu-latest
    steps:
      - name: Save PR number
        run: |
          echo ${{ github.event.pull_request.number || github.event.issue.number }} > pr_number.txt
      - name: Upload PR number
        uses: actions/upload-artifact@v4
        with:
          name: pr_number
          path: pr_number.txt
