name: unit-test

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'app-ios/**'

run-name: "unit-test by ${{ github.actor }}"

permissions: { }

jobs:
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      contents: read # for clone
      actions: write # for upload-artifact

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - uses: ./.github/actions/setup-java

      - name: Upload an event payload for EnricoMi/publish-unit-test-result-action
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: event-payload
          path: ${{ github.event_path }}

      - run: ./gradlew testDevDebugUnitTest testDebugUnitTest --stacktrace

      - run: |
          ./gradlew \
                :core:data:iosSimulatorArm64Test \
                :core:model:iosSimulatorArm64Test \
                --stacktrace

      # Saving cost
      # - run: ./gradlew koverHtmlReportDevDebug --stacktrace

      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        if: always()
        with:
          name: test-reports
          path: |
            **/reports
            **/build/outputs/roborazzi
